adaptlearning/adapt-contrib-media

js/adapt-contrib-media.js
=> Fixed invalid require call

bower.json, js/adapt-contrib-media.js, package.json, properties.schema
=> Added _supportedLayout

templates/media.hbs
=> Fixes ABU-486

less/media.less
an issue has been intermittently occuring to do with black lines
appearing on the sides of some videos that sit inside the video player.
this was because the video player had a black background. I've now set
the background to transparent to avoid this.
=> issue with black lines around videos

templates/media.hbs
https://adaptlearning.atlassian.net/browse/ABU-594
=> Added statement to include transcriptButton aria or not

js/adapt-contrib-media.js
Added a check around the _accessibility attribute, previously the code was failing when this was not set.
=> Fixes #108 - supports content from Adapt v1.x

js/adapt-contrib-media.js
Stops all transcripts on page being opened at once. Fixes https://adaptlearning.atlassian.net/browse/ABU-1016.
=> Fix reference to transcript divs

README.md
make the bit about IE8 a bit clearer, add something about play and completion events not working when source is vimeo (see ABU-1022)
=> add further info to limitations section

templates/media.hbs
Base class not required on these buttons
=> Removed base class from buttons

js/adapt-contrib-media.js
hide controls on default and with mouseover unless otherwise specified or accessibility is on
=> bugfix/hide-controls: default to hide controls

README.md, example.json, js/adapt-contrib-media.js, properties.schema
=> Inline transcript triggers completion

README.md, js/adapt-contrib-media.js, properties.schema
* Have removed dependency on accessibility
* Set complete on transcript as default
* Allowed user to override in settings
* Updated schema to match
=> #898 Set complete on transcript as default

js/adapt-contrib-media.js, js/mediaelement-and-player-accessible-captions.js, less/media.less, properties.schema
* added patch for closed captions buttons
* added patch for fullscreen
=> issue-983 accessible closed captions + issue-854 fullscreen fixes

js/adapt-contrib-media.js
Added defensive programming around incorrectly configured media component to avoid infinite spinners on course page load.
=> Issue-1076

js/adapt-contrib-media.js
fixes #1081 https://github.com/adaptlearning/adapt_framework/issues/1081
=> resize window on transcript toggle

properties.schema
Both 'src' and 'srcLang' should be required.
=> Tidied up validation on closed captions object

README.md, properties.schema
Resolves https://github.com/adaptlearning/adapt_authoring/issues/1326.
=> Update _playerOptions to work with JSON editor

js/adapt-contrib-media.js
https://github.com/adaptlearning/adapt_framework/issues/1223
Credit should go to @oliverfoster
=> Partial fix for issue/#1223

assets/froogaloop.js, js/adapt-contrib-media.js, js/mediaelement-and-player.js
* vimeo cleanup
* missing function call removed
* event and player cleanups
=> issue-1223-1: memory leak fixes

less/media.less
https://github.com/adaptlearning/adapt_framework/issues/1234
=> issue-1234: fix accessibility focus rect

README.md, example.json, properties.schema, templates/media.hbs
add playsinline attribute to allow playing videos inline on iOS
=> iOS playsinline 

js/adapt-contrib-media.js
adaptlearning/adapt_framework#1412
=> Amend so external transcripts can also be used to set completion.

js/adapt-contrib-media.js
https://github.com/adaptlearning/adapt_framework/issues/1449
=> issue/1449: added "media:stop" listener

js/adapt-contrib-media.js, properties.schema
https://github.com/adaptlearning/adapt_framework/issues/1598
=> issue/1598: update media:stop behaviour

README.md, bower.json, properties.schema
Changed type input property to select dropdown menu
=> fixes #1622

README.md, bower.json
https://github.com/adaptlearning/adapt_framework/issues/1704
=> Version bump to 2.1.1

js/adapt-contrib-media.js
https://github.com/adaptlearning/adapt_framework/issues/1718
=> Stopped the currently-running animation on transcript button

less/media.less
fixes https://github.com/adaptlearning/adapt_framework/issues/1986
=> amend path to assets folder

less/media.less, less/mep.less
fixes https://github.com/adaptlearning/adapt_framework/issues/2024
=> issue/#2024: Video controls disappear in iOS 11

js/adapt-contrib-media.js
mediaElement was null on page loading on this particular IE version.
=> fix null reference on IE v11.0.9600.18738

js/adapt-contrib-media.js
part of adaptlearning/adapt_framework#2269
=> switch over to the new ComponentView inview functionality

js/adapt-contrib-media.js
and added a missing semi-colon
=> updated to use ComponentModel

js/adapt-contrib-media.js
[#2344](https://github.com/adaptlearning/adapt_framework/issues/2344)
=> #2344 add global triggers for play, pause and ended events

less/media.less, templates/media.hbs
Makes sense as a feature. I remember we did this at Kineo. Double check for both the mp3 file and for the poster so nothing will change unless the user is searching for it
[#2264](https://github.com/adaptlearning/adapt_framework/issues/2264)
=> Poster image with audio

js/adapt-contrib-media.js, templates/media.hbs
plus general tidy-up of indentation
=> use four spaces for indentation

js/adapt-contrib-media.js
Queue a media event first to see if it should be fired. This:
- Prevents pause firing when ended
- Prevents play/pause firing simultaneously when user seeks
=> Resolves #2357 debounce video events

js/adapt-contrib-media.js
fixes https://github.com/adaptlearning/adapt_framework/issues/2427
=> add slight delay to call to focus transcript button

js/adapt-contrib-media.js
fixes https://github.com/adaptlearning/adapt_framework/issues/2418
=> Fix: stuck in infinite loading loop when no media is selected

js/adapt-contrib-media.js
See adaptlearning/adapt_framework#2477.
=> Amends to allow iOS native controls within mediaElement

libraries/mediaelement-fullscreen-hook.js
https://github.com/adaptlearning/adapt_framework/issues/2557
=> remove vendor prefixes where no longer required

less/media.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891
=> Less tidy up

js/adapt-contrib-media.js, less/media.less, less/mep-overrides.less
Resolves: https://github.com/adaptlearning/adapt_framework/issues/2895
* Moved mep specific overrides to a new file
* Tweaked required overrides in media.less
* Bug fix external source class selector
=> mep override refactor

templates/media.hbs
fixes https://github.com/adaptlearning/adapt_framework/issues/2969
=> remove class a11y-ignore-aria

js/adapt-contrib-media.js
There were so many (355!) eslint issues that just viewing this file was hurting my eyes, with so much error highlighting! All should now be fixed.
When reviewing: please note, the aim of this was to do just enough to clear the eslint errors. I'm sure you will spot plenty of ways this could be further improved but really I would prefer to do that as a separate job!
=> clean up eslint issues

less/media.less
fixes https://github.com/adaptlearning/adapt_framework/issues/3110
=> prevent resize between poster image and video transition

README.md, example.json, properties.schema, templates/media.hbs
Resolves https://github.com/adaptlearning/adapt_framework/issues/3159
* Added support for square and portrait aspect ratio
=> Added square and portrait aspect ratio

js/mediaView.js
Fixes https://github.com/adaptlearning/adapt_framework/issues/3202.
=> Switch to widget for inview listener

js/mediaView.js
https://github.com/adaptlearning/adapt-contrib-media/issues/226
=> issue/226 Fix for inview media functionality

js/mediaView.js, properties.schema, schema/course.schema.json
fixes https://github.com/adaptlearning/adapt_framework/issues/2822
* Translatable aria-labels for media element user interface
=> issue/2822 Added translatable aria-labels

less/mep.less
Fixes: #244 
* Converted `:focus` to `:focus-visible`
=> Update: Converted focus to focus-visible (fixes #244)

properties.schema, schema/component.schema.json
#245 
* default instruction text provided
=> New: Provide default instruction text (fixes #245)

js/mediaView.js, libraries/mediaelement-and-player.js
Fixes (#250)
* Implemented the suggested fix in #250 to allow screen readers to announce the closed caption button's pressed state with aria-pressed  
* ESLint on save
[//]: # (List appropriate steps for testing if needed)
1. Navigate to media component
2. Using a screen reader toggle captions on/off 
[//]: # (Mention any other dependencies)
=> Fix: aria-pressed added to closed caption button.

js/mediaView.js
* Adds media trigger if user completes via the transcript button and if that option is enabled.
* Fixes #253 
[//]: # (List appropriate steps for testing if needed)
1. Install PR and use browser console to test.
[//]: # (Mention any other dependencies)
=> New: Added event trigger (fixes: #253)

js/mediaView.js
#267 
Linked to Jest testing (https://github.com/adaptlearning/adapt_framework/pull/3383)
* Overwrite mediaelement-and-player functions to remove global delete (#267)
=> Fix: overwrite mediaelement-and-player functions to remove global delete (fixes #267)

js/mediaView.js
#273 
* Check number of captions before applying toggle-captions class (fixes #273)
=> Fix: Check number of captions before applying toggle-captions class (#273)

example.json, js/mediaView.js
#276 
* alwaysShowControls default changed to true (fixes #276)
=> Fix: alwaysShowControls default changed to true (fixes #276)

schema/component.schema.json
#281 
* Schema media updated for transcript and closed captions from 'other' to 'text' (fixes #281)
=> Fix: Schema media updated for transcript and closed captions from 'other' to 'text' (fixes #281)

test/e2e/media.cy.js
=> Chore: e2e tests on media component (issue/286)

js/mediaView.js
* Adds new trigger to capture transcript toggles
* Adjusts transcript completion so it only triggers when it completes the component
* fixes #283
=> Update: Adjusts transcript triggers (fixes #283)

migrations/v2.js, migrations/v4.js, migrations/v5.js, migrations/v6.js
#314 
* New: Migration scripts added to repo (fixes #314)
=>  New: Migration scripts added to repo (fixes #314) 

bower.json, package-lock.json, package.json
#325 
Part of - https://github.com/adaptlearning/adapt_framework/issues/3698
* package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #325)
=> Update: package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #325)

bower.json, package.json
Fixes #324 
* Bumping required FW version for using .visually-hidden-focusable()
=> Fix: Bumping required FW version for using .visually-hidden-focusable()

js/mediaView.js
#341 
* Add guarded read of model attribute to fix typo
=> Fix: Add guarded read of model attribute to fix typo
