adaptlearning/adapt-contrib-media

example.json, properties.schema, templates/media.hbs
Closed caption feature with only the template `hbs` changes so it can fit with the PR https://github.com/adaptlearning/adapt-contrib-media/pull/85 which externalises the features of the media player.
=> Lukasz Grela - Closed Captions feature

README.md
make the bit about IE8 a bit clearer, add something about play and completion events not working when source is vimeo (see ABU-1022)
=> add further info to limitations section

less/media.less, templates/media.hbs
Since a is changed to button, width gets reduced. So it is set to 100% in media-inline-transcript-button class
=> a to button

properties.schema
`_startLanguage` and all transcript properties aren't required for this component to work
=> amend various properties to be optional

js/adapt-contrib-media.js
* onPlayerReady doesn't callback until the video video is visible onscreen
this makes it tabbable when it does callback
=> issue-1231: give vimeo mejs-container tabbing

README.md, properties.schema, templates/media.hbs
OGV support isn't as required as it used to be (http://caniuse.com/#search=ogv) as most browsers that support it also support MP4 (http://caniuse.com/#search=mp4).
=> Conditional media sources, support for .webm

js/adapt-contrib-media.js
YouTube and Vimeo give share links with HTTPS, by removing the protocol from the URL it prevents any problems with the protocol not matching the server on which the Adapt content is hosted.
=> Removed the protocol from streaming services

js/adapt-contrib-media.js
Rather then having global events for media events, I decided to add player state attributes to each model.
One can then listen to the change event of each media component models.
=> expose media events

properties.schema
The word video is used several times as an all encompassing word for what could also be an audio file. Should use the generic term `media` instead.
=> Reworded video to media

README.md, js/adapt-contrib-media.js, properties.schema
The option '_preventForwardScrubbing' prevents users from skipping to the end of required media components in order to continue on to the next component. If the option '_preventForwardScrubbing' is set to 'true' this prevents users from scrubbing ahead any further than they have already viewed unless the user has completed the unit.  They can freely scrub backwards, and back up until the furthest viewed point.  While there are still possibilities for navigating around this, it removes the most obvious route for users to attempt to circumvent required learning materials.
=> Controlled media scrub

js/adapt-contrib-media.js, libraries/mediaelement-fullscreen-hook.js
https://github.com/adaptlearning/adapt_framework/issues/1478
=> issue-1470: fullscreen hook + inview control

less/media.less
Override the default hover state for 'mejs-overlay' and tie it to Modernizr's 'no-touch' class to stop the hover state from appearing on touch devices.
=> mejs-overlay hover state bug fix

js/adapt-contrib-media.js
By forcing remote media to use a relative protocol, it causes the content to fail to load if it is running over a protocol other than `http:` or `https:` (e.g. `file:`). (Additionally, the use of relative protocols is considered an anti-pattern by some: https://www.paulirish.com/2010/the-protocol-relative-url/).
This only changes the source if the page is being loaded over a secure connection and the remote content is not; to avoid accidentally loading Mixed Content, it attempts to load the asset over https instead.
=> Avoid use of relative protocol when loading remote media

js/adapt-contrib-media.js, templates/media.hbs
The Media component currently changes the DOM structure when the transcript button is opened or closed. This change makes the `transcript-text-container` be updated instead which keeps the DOM structure the same.
resolves https://github.com/adaptlearning/adapt_framework/issues/2062
=> Updated to only change the button text

bower.json, js/adapt-contrib-media.js, less/media.less, templates/media.hbs
see https://github.com/adaptlearning/adapt_framework/issues/2284
Well, this took a lot longer than I thought as I'd completely forgotten that the media component supports multiple caption languages!
On the off chance that media component 'a' has a captions language that's not present in media component 'b' - and the user selects that language, 'b' will default to whatever language is set in `_startLanguage`. If that's not set, it will simply turn its own captions off. The actual language the user chose will be the one stored in `offlineStorage`.
also fixes https://github.com/adaptlearning/adapt_framework/issues/1883 - would be interested to get some comments on how I have implemented this (using `className` function in adapt-contrib-media.js) - the alternative would be to do this:
which …
=> have media component remember learner's choice of captions

README.md, bower.json, example.json, js/adapt-contrib-media.js, properties.schema
In response to [#2128](https://github.com/adaptlearning/adapt_framework/issues/2128).
As per [this comment](https://github.com/adaptlearning/adapt_framework/issues/2128#issuecomment-396867757) media component is paused directly, rather than triggering `media:stop`.
=> #2128 trigger pause when media component leaves view

templates/media.hbs
so that it's only available to screen reader users
fixes https://github.com/adaptlearning/adapt_framework/issues/2419
=> remove skip to transcript button from tab order

js/adapt-contrib-media.js
fixes [#2431](https://github.com/adaptlearning/adapt_framework/issues/2431)
aria-valuemax="NaN" causes an error in a Lighthouse accessibility audit, this fixes by replacing with 0 post-render.
=> Ensure aria-valuemax is set to a valid value

templates/media.hbs
the `if_value_equals` helper is deprecated (since FW v4.4.0)
=> drop use of deprecated helper if_value_equals

js/mediaView.js
Resolves https://github.com/adaptlearning/adapt_framework/issues/3137
* Added aria hidden attribute to media overlay play btn to remove it from the tab order
=> Add aria hidden attribute to overlay play btn

bower.json, js/mediaView.js
https://github.com/adaptlearning/adapt_framework/issues/3009
=> Move from centralised singleton to imported singletons

js/adapt-contrib-media.js, js/mediaView.js, libraries/mediaelement-fullscreen-hook.js, templates/media.hbs
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to components.register from Adapt.register
* Use `offlineStorage`, `a11y`, `device` and `logging` directly
* Switched to `equals` helper from `if_value_equals`
=> issue/2799 Remove redundant behaviour

js/mediaView.js
#231 Assigns the media container a role of 'region' instead of 'application'. Also uses the title and displayTitle as a label for aria context when learners focus on the media container.
=> issue/231 - Add region role to video container

less/mep-overrides.less
fixes https://github.com/adaptlearning/adapt-contrib-media/issues/248 
When a video is run fullscreen on an Android device, in portrait orientation, the aspect ratio of the video is incorrect as it is stretched to fill the viewport and distorts the video. 
This doesn't occur if using native Android controls via `_playerOptions.AndroidUseNativeControls: true`. The issue is restricted to Android only as iOS switches to native controls automatically when run fullscreen.
=> Fix: contain fullscreen video when in portrait mode (fixes #248)

js/mediaView.js, libraries/mediaelement-and-player.js
Fixes #255 
* Removes a fix for Chrome versions 16 and below. This was causing the initial issue with fullscreen video.
See #255
=> Fix: Chrome automatically exits full screen video if zoom is not 100% (fixes #255)

less/media.less, templates/media.hbs
Fixes #262 
* Makes the 'skip to transcript' button visible on keyboard focus.
=> Fix: Make 'skip to transcript' button visible on focus (fixes #262)

js/mediaView.js
* Adds trigger to volume controls to indicate the mute state and current volume value
* Fixes #264 
[//]: # (List appropriate steps for testing if needed)
1. Install PR and use browser console to test.
[//]: # (Mention any other dependencies)
=>  New: Added event trigger (fixes: #264)

js/mediaLibrariesOverrides.js, js/mediaView.js
fixes #271 
* Made `purge` globally accessible at `window.mejs.purge`
* Performed linting corrections on mediaLibrariesOverrides.js
Original code breaks when navigating away from Presentation Components to the menu, on destruction of mediaView line 399
https://github.com/adaptlearning/adapt-contrib-media/blob/01fadeced8650c7aeab9f23915488f10eb6caaec/js/mediaView.js#L399
This is as the function `purge` lives in a different file:
https://github.com/adaptlearning/adapt-contrib-media/blob/01fadeced8650c7aeab9f23915488f10eb6caaec/js/mediaLibrariesOverrides.js#L27-L43
=> Fix: Exposed purge globally, linting (fixes #271)

less/media.less, templates/media.hbs
Fixes https://github.com/adaptlearning/adapt-contrib-media/issues/290
* On completion, a checkmark icon is displayed on the transcript button
* Transcript button styled for consistency with `.nav__btn` text label/icon
* LESS styles structured in DOM order (skip to transcript btn, transcript btn, transcript body)
**Not included in PR**
Do you think we should display a plus icon for the inline transcript button to convey the button toggles/expands to reveal content? This would be consistent with the Accordion item button however I'm not wedded to this if people think it's unnecessary.  See example below.
=> New: completion icon added to transcript button (fixes #290)

test/e2e/media.cy.js
=> Fix: Update tests to meet new standards (fixes #294)

test/e2e/media.cy.js
Fixes #300 
* Tests now account for scenarios where _externalTranscript is turned on or _inlineTranscript is turned off
=> Fix: Tests now account for scenarios where _externalTranscript is turned on or _inlineTranscript is turned off

js/mediaLibrariesOverrides.js, js/mediaView.js
Suggested changes for your loading sequences @swashbuck
=> issue/298 client-side loading amends

schema/component.schema.json
#309 
* isObjectId removed from schema to allow external assets to be added (fixes #309)
=>  Fix: isObjectId removed from schema to allow external assets to be added (fixes #309)

js/mediaLibrariesOverrides.js, js/mediaView.js
requires https://github.com/adaptlearning/adapt-contrib-core/issues/612
fixes #304 
* `import()` returns a promise
* android triggers `timeupdate` before `seeking` which prevents the seek blocking behaviour
* `defaultSeekBackwardInterval` and `defaultSeekForwardInterval` need to be converted to functions from strings at runtime
* `onMediaElementTimeUpdate` and `onMediaElementSeeking` do not have `event.target` on windows chrome use `event.currentTarget` instead
* inview + fullscreen locking
=> Fix: Default seek, event.target, import await, forward scrubbing, fullscreen inview

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_template.md
Fixes https://github.com/adaptlearning/adapt-contrib-media/issues/315
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
=> Chore: Add support for new issue experience (fixes #315)

less/media.less
Fix #312 
1. Ensure "Skip to transcript" button does not take up space until in focus
2. Add bottom margin to button when visible
1. Using keyboard navigation, tab until you come to a "Skip to transcript" button.
=> Fix: "Skip to transcript" button spacing (fixes #312)

js/mediaView.js
It seems that learners are bypassing the `_preventForwardScrubbing` setting by interacting with the locked media player scrub bar. Despite the setting being enabled, a small number of learners repeatedly select the scrub bar and are able to skip forward in the video, essentially bypassing the need to watch the content in full.
The issue likely stems from the current solution, which forces the scrub bar to the furthest point of progress, but this approach isn't fully effective. A more robust solution would be to ensure …
=> Fix: Preventing forward scrubbing (fixes: #319)

less/media.less
Fixes https://github.com/adaptlearning/adapt-contrib-media/issues/317
* Replaced `:focus-visible` styles with core mixin [`.visually-hidden-focusable`](https://github.com/adaptlearning/adapt-contrib-core/blob/d088744562af42232911f13391c47959d7dca415/less/core/accessibility.less#L36). To ensure consistency within Adapt when styling visually hidden / focused elements.
See [Core PR](https://github.com/adaptlearning/adapt-contrib-core/pull/611) for reference where accessible mixins were updated inline with latest best practice.
@simondate, this also addresses the [border issue](https://github.com/adaptlearning/adapt-contrib-media/issues/317#issuecomment-2846835640) you raised.
=> Update: "skip to transcript" styles to reflect latest core a11y (fixes #317)

schema/component.schema.json
Fixes #330
* Allows all non audio/image/video files to be selectable in the AAT for the transcript files
=> Fix: Switch transcript AAT asset filter to 'other' (fixes #330)

js/mediaView.js
Fixes https://github.com/adaptlearning/adapt-contrib-media/issues/337
* Apply completion aria label to transcript button when Media completes. 
* This provides the screen reader equivalent of the visual tick icon and is consistent with other completed items/buttons.
1. With a screen reader running, complete the Media component by either opening the transcript or playing the video.
2. When focus is one the transcript button, this should announce "Completed. Transcript" / "Completed. Close Transcript" or equivalent.
=> Fix: Apply completion aria label to transcript button (fixes #337)
